// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.1
// source: protos/everphone.proto

package everphone

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EverphoneClient is the client API for Everphone service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EverphoneClient interface {
	RandomText(ctx context.Context, in *EverphoneRandomTextInput, opts ...grpc.CallOption) (*EverphoneRandomTextOutput, error)
}

type everphoneClient struct {
	cc grpc.ClientConnInterface
}

func NewEverphoneClient(cc grpc.ClientConnInterface) EverphoneClient {
	return &everphoneClient{cc}
}

func (c *everphoneClient) RandomText(ctx context.Context, in *EverphoneRandomTextInput, opts ...grpc.CallOption) (*EverphoneRandomTextOutput, error) {
	out := new(EverphoneRandomTextOutput)
	err := c.cc.Invoke(ctx, "/Everphone/RandomText", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EverphoneServer is the server API for Everphone service.
// All implementations must embed UnimplementedEverphoneServer
// for forward compatibility
type EverphoneServer interface {
	RandomText(context.Context, *EverphoneRandomTextInput) (*EverphoneRandomTextOutput, error)
	mustEmbedUnimplementedEverphoneServer()
}

// UnimplementedEverphoneServer must be embedded to have forward compatible implementations.
type UnimplementedEverphoneServer struct {
}

func (UnimplementedEverphoneServer) RandomText(context.Context, *EverphoneRandomTextInput) (*EverphoneRandomTextOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RandomText not implemented")
}
func (UnimplementedEverphoneServer) mustEmbedUnimplementedEverphoneServer() {}

// UnsafeEverphoneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EverphoneServer will
// result in compilation errors.
type UnsafeEverphoneServer interface {
	mustEmbedUnimplementedEverphoneServer()
}

func RegisterEverphoneServer(s grpc.ServiceRegistrar, srv EverphoneServer) {
	s.RegisterService(&Everphone_ServiceDesc, srv)
}

func _Everphone_RandomText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EverphoneRandomTextInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EverphoneServer).RandomText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Everphone/RandomText",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EverphoneServer).RandomText(ctx, req.(*EverphoneRandomTextInput))
	}
	return interceptor(ctx, in, info, handler)
}

// Everphone_ServiceDesc is the grpc.ServiceDesc for Everphone service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Everphone_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Everphone",
	HandlerType: (*EverphoneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RandomText",
			Handler:    _Everphone_RandomText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/everphone.proto",
}
