version: '3.2'
services:
  phpclient:
    image: grpc-demo/phpclient
    tty: true
    build:
      context: phpclient
      dockerfile: Dockerfile
    working_dir: /root/app/
    volumes:
      - "./protos:/root/app/protos:cached"
      - "./phpclient:/root/app/src:cached"
  goclient:
    image: grpc-demo/goclient
    tty: true
    build:
      context: goclient
      dockerfile: Dockerfile
    working_dir: /root/app/
    volumes:
      - "./goclient:/root/app/src"
  goserver:
    image: grpc-demo/goserver
    build:
      context: goclient
      dockerfile: Dockerfile
    working_dir: /root/app/src
    command: go run ./cmd/server/main.go
    volumes:
      - "./goserver:/root/app/src"
    ports: [ '127.0.0.1:8080:8080' ]