<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: everphone.proto

namespace EverphoneDemo\Meta;

class Everphone
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ù
everphone.proto"(
EverphoneRandomTextInput
Text (	")
EverphoneRandomTextOutput
Text (	2P
	EverphoneC

RandomText.EverphoneRandomTextInput.EverphoneRandomTextOutputB2Z./everphone EverphoneDemo‚EverphoneDemo\\Metabproto3'
        , true);

        static::$is_initialized = true;
    }
}

